version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/temp
permissions:
   - object: /var/www/temp
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - file 
       - directory
hooks:
  BeforeInstall:
    - location: scripts/mv_old_version
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_software
      timeout: 300
      runas: root
