#!/bin/bash
#cd /etc/
#mv letsencrypt letsencrypt.old
#aws s3 cp s3://conexpar-infra/letsencrypt/letsencrypt.tar.gz /etc/letsencrypt.tar.gz
#tar -xvzf letsencrypt.tar.gz

DATE=`date +%Y%m%d%H%M`

if [ "$DEPLOYMENT_GROUP_NAME" == "int.shokinfractrl" ]
then
        touch -t $DATE /var/www/int.shokinfractrl/*/*/*/*
        mv /var/www/temp /var/www/int.shokinfractrl
	chown www-data.www-data /var/www/int.shokinfractrl/
	chown www-data.www-data /var/www/int.shokinfractrl/* -R
	chown www-data.www-data /var/www/int.shokinfractrl/.[a-z]* -R
	chmod 775 /var/www/int.shokinfractrl -R
	chmod 777 /var/www/int.shokinfractrl/storage -R
	touch -t $DATE /var/www/int.shokinfractrl/*/*/*/*
        find /var/www/int.shokinfractrl/ -name "*.php" | xargs dos2unix
        find /var/www/int.shokinfractrl/ -name "*.js" | xargs dos2unix
        find /var/www/int.shokinfractrl/ -name "*.css" | xargs dos2unix
	service nginx restart
	cd /var/www/int.shokinfractrl/
fi

if [ "$DEPLOYMENT_GROUP_NAME" == "uat.shokinfractrl" ]
then
        #touch -t $DATE /var/www/uat.shokinfractrl/*/*/*/*
        mv /var/www/temp /var/www/uat.shokinfractrl
        chown www-data.www-data /var/www/uat.shokinfractrl/
        chown www-data.www-data /var/www/uat.shokinfractrl/* -R
        chown www-data.www-data /var/www/uat.shokinfractrl/.[a-z]* -R
	chmod 775 /var/www/uat.shokinfractrl -R
        chmod 777 /var/www/uat.shokinfractrl/storage -R
        touch -t $DATE /var/www/uat.shokinfractrl/*/*/*/*
	find /var/www/uat.shokinfractrl/  -name "*.php" | xargs dos2unix
        find /var/www/uat.shokinfractrl/  -name "*.js" | xargs dos2unix
        find /var/www/uat.shokinfractrl/ -name "*.css" | xargs dos2unix
        service nginx restart
        cd /var/www/uat.shokinfractrl/
fi

if [ "$DEPLOYMENT_GROUP_NAME" == "pro.shokinfractrl" ]
then
        #touch -t $DATE /var/www/uat.shokinfractrl/*/*/*/*
        mv /var/www/temp /var/www/pro.shokinfractrl
        chown www-data.www-data /var/www/pro.shokinfractrl/
        chown www-data.www-data /var/www/pro.shokinfractrl/* -R
        chown www-data.www-data /var/www/pro.shokinfractrl/.[a-z]* -R
        chmod 775 /var/www/pro.shokinfractrl -R
        chmod 777 /var/www/pro.shokinfractrl/storage -R
        touch -t $DATE /var/www/pro.shokinfractrl/*/*/*/*
        find /var/www/pro.shokinfractrl/  -name "*.php" | xargs dos2unix
        find /var/www/pro.shokinfractrl/  -name "*.js" | xargs dos2unix
        find /var/www/pro.shokinfractrl/ -name "*.css" | xargs dos2unix
        service nginx restart
        cd /var/www/pro.shokinfractrl/
fi


